In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.linear_model import LinearRegression
from sklearn.utils import shuffle

In [3]:
data = pd.read_csv("student-mat.csv")

In [4]:
data = data[["G1", "G2", "G3", "studytime", "failures", "absences"]]

In [5]:
predict = "G3"
x = np.array(data.drop([predict], 1))
y = np.array(data[predict])

C:\Users\darkp\AppData\Local\Temp/ipykernel_5720/2796477508.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  x = np.array(data.drop([predict], 1))


In [6]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2)

In [7]:

linear_regression = LinearRegression()
linear_regression.fit(xtrain, ytrain)

LinearRegression()

In [8]:
import pickle
with open("pickle_model", "wb") as file:
    pickle.dump(linear_regression, file)

# # use the saved model

In [9]:

with open("pickle_model", "rb") as file:
    model = pickle.load(file)

In [10]:
predictions = model.predict(xtest)

In [11]:
for i in range(len(predictions)):
    print(predictions[x], xtest[x], [ytest[x]])

[[ 8.44627293 -0.31075489 13.38215197  9.45231125 -0.31075489]
 [ 8.44627293  8.44627293 13.38215197  9.45231125  9.20804151]
 [16.32500525 13.60629016 13.38215197  7.17953679 10.68055861]
 ...
 [10.68055861 13.60629016 13.47163616  7.17953679  7.17953679]
 [10.21783699 19.6835305  13.47163616  9.45231125  9.45231125]
 [13.60629016 10.66858133 13.47163616  9.45231125  8.44627293]] [[[10  9  3  0  2]
  [10  0  2  0  0]
  [15 13  3  2 14]
  [10 10  2  0  2]
  [10  0  2  0  0]]

 [[10  9  3  0  2]
  [10  9  3  0  2]
  [15 13  3  2 14]
  [10 10  2  0  2]
  [ 8 10  2  0  4]]

 [[17 16  2  0  0]
  [12 14  1  0  0]
  [15 13  3  2 14]
  [ 8  8  1  1  4]
  [10 11  4  0 10]]

 ...

 [[10 11  4  0 10]
  [12 14  1  0  0]
  [15 13  2  0  9]
  [ 8  8  1  1  4]
  [ 8  8  1  1  4]]

 [[ 9 11  3  0  2]
  [18 19  1  0  6]
  [15 13  2  0  9]
  [10 10  2  0  2]
  [10 10  2  0  2]]

 [[12 14  1  0  0]
  [11 11  2  0  4]
  [15 13  2  0  9]
  [10 10  2  0  2]
  [10  9  3  0  2]]] [array([[ 8,  0, 13, 10,  0]